# This Config Controls what plugins work on certain worlds.
# Example
# limit:
#   WorldEdit:
#     - world
#     - world_nether
#   Essentials: []
# This will make it so worldedit will only work in world & world_nether, meaning in the end it is not usable.
# When there is no worlds in the list it will allow it for any worlds, in this example allowing all worlds.
# Whenever a plugin is added, this config will automatically add it!
limit: {}