name: PerWorldPlugins
main: us.Myles.PWP.Plugin
description: Allows Plugin events to be fired only in certain worlds
version: 1.0.6
author: _Myles
commands:
  pwp:
    description: Commands for PerWorldPlugins
    usage: /pwp reload | version