name: PerWorldPlugins
main: us.Myles.PWP.Plugin
description: Allows Plugin events to be fired only in certain worlds
version: 1.2.0
author: _MylesC
commands:
  pwp:
    description: Commands for PerWorldPlugins
    usage: /pwp reload | version