name: PerWorldPlugins
main: us.Myles.PWP.Plugin
description: Allows you to control which worlds that your plugins will receive events in.
version: 1.2.0
authors: [_MylesC, Incomprehendable]
commands:
  pwp:
    description: Commands for PerWorldPlugins
    usage: /pwp reload | version